// Generated by Grafana k6 Studio (1.13.1) on 2026-05-31T09:35:20.612Z

import { group, sleep, check } from "k6";
import http from "k6/http";
import execution from "k6/execution";

export const options = {
  stages: [
    { target: 20, duration: "1m" },
    { target: 20, duration: "3m30s" },
    { target: 0, duration: "1m" },
  ],
};

export default function () {
  let params;
  let resp;
  let match;
  let regex;
  let url;
  const correlation_vars = {};

  group("Default group", function () {
    params = {
      headers: {
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`https://www.saucedemo.com/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `text/css,*/*;q=0.1`,
        referer: `https://www.saucedemo.com/`,
      },
      cookies: {},
    };

    url = http.url`https://www.saucedemo.com/static/css/main.8a7d64a1.css`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `*/*`,
        referer: `https://www.saucedemo.com/`,
      },
      cookies: {},
    };

    url = http.url`https://www.saucedemo.com/static/js/main.bcf4bc5f.js`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `*/*`,
        referer: `https://www.saucedemo.com/`,
      },
      cookies: {},
    };

    url = http.url`https://www.saucedemo.com/manifest.json`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://www.saucedemo.com/`,
      },
      cookies: {},
    };

    url = http.url`https://www.saucedemo.com/favicon.ico`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Content-type": `application/json`,
        Accept: `*/*`,
        Referer: `https://www.saucedemo.com/`,
      },
      cookies: {},
    };

    url = http.url`https://events.backtrace.io/api/unique-events/submit?universe=UNIVERSE&token=TOKEN`;
    resp = http.request(
      "POST",
      url,
      `{"application":"Swag Store","appversion":"3.0.0","unique_events":[{"timestamp":1780219510,"attributes":{"application.session":"27589fe0-8ff0-4c7e-9496-31ffc5b8598d","backtrace.agent":"@backtrace-labs/react","backtrace.version":"0.0.5","browser.name":"Chrome","browser.version":"148.0.0.0","engine.name":"Blink","engine.version":"148.0.0.0","browser.platform":"Win32","cpu.arch":"amd64","uname.sysname":"Windows","uname.version":"10","mobile":"false","user.agent.full":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36","application":"Swag Store","process.age":"0","hostname":"www.saucedemo.com","referrer":"https://www.saucedemo.com/","location.port":"","location.protocol":"https:","location.origin":"https://www.saucedemo.com","location.href":"https://www.saucedemo.com/","language":"en-US","cookies.enable":"true","document.domain":"www.saucedemo.com","document.baseURI":"https://www.saucedemo.com/","document.title":"Swag Labs","document.referrer":"","localstorage.enable":"true","window.innerHeight":"703","window.innerWidth":"1036","window.outerHeight":"798","window.outerWidth":"1051","window.pageXOffset":"0","window.pageYOffset":"0","window.screenX":"10","window.screenY":"10","window.screenLeft":"10","window.screenTop":"10","guid":"27589fe0-8ff0-4c7e-9496-31ffc5b8598d","application.version":"3.0.0"},"unique":["guid"]}],"metadata":{"dropped_events":0}}`,
      params,
    );

    check(resp, { "status equals 401": (r) => r.status === 401 });

    params = {
      headers: {
        "Content-type": `application/json`,
        Accept: `*/*`,
        Referer: `https://www.saucedemo.com/`,
      },
      cookies: {},
    };

    url = http.url`https://events.backtrace.io/api/summed-events/submit?universe=UNIVERSE&token=TOKEN`;
    resp = http.request(
      "POST",
      url,
      `{"application":"Swag Store","appversion":"3.0.0","summed_events":[{"timestamp":1780219510,"attributes":{"application.session":"27589fe0-8ff0-4c7e-9496-31ffc5b8598d","backtrace.agent":"@backtrace-labs/react","backtrace.version":"0.0.5","browser.name":"Chrome","browser.version":"148.0.0.0","engine.name":"Blink","engine.version":"148.0.0.0","browser.platform":"Win32","cpu.arch":"amd64","uname.sysname":"Windows","uname.version":"10","mobile":"false","user.agent.full":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36","application":"Swag Store","process.age":"0","hostname":"www.saucedemo.com","referrer":"https://www.saucedemo.com/","location.port":"","location.protocol":"https:","location.origin":"https://www.saucedemo.com","location.href":"https://www.saucedemo.com/","language":"en-US","cookies.enable":"true","document.domain":"www.saucedemo.com","document.baseURI":"https://www.saucedemo.com/","document.title":"Swag Labs","document.referrer":"","localstorage.enable":"true","window.innerHeight":"703","window.innerWidth":"1036","window.outerHeight":"798","window.outerWidth":"1051","window.pageXOffset":"0","window.pageYOffset":"0","window.screenX":"10","window.screenY":"10","window.screenLeft":"10","window.screenTop":"10","guid":"27589fe0-8ff0-4c7e-9496-31ffc5b8598d","application.version":"3.0.0"},"metric_group":"Application Launches"}],"metadata":{"dropped_events":0}}`,
      params,
    );

    check(resp, { "status equals 401": (r) => r.status === 401 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://www.saucedemo.com/inventory.html`,
      },
      cookies: {},
    };

    url = http.url`https://www.saucedemo.com/static/media/menu3x.52cc17a327296e6394f33e8c20abc62c.svg`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://www.saucedemo.com/inventory.html`,
      },
      cookies: {},
    };

    url = http.url`https://www.saucedemo.com/static/media/close@3x.a30a8a1db39c69f50a19aa3c34876918.svg`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://www.saucedemo.com/inventory.html`,
      },
      cookies: {},
    };

    url = http.url`https://www.saucedemo.com/static/media/sauce-backpack-1200x1500.0a0b85a385945026062b.jpg`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://www.saucedemo.com/inventory.html`,
      },
      cookies: {},
    };

    url = http.url`https://www.saucedemo.com/static/media/bike-light-1200x1500.37c843b09a7d77409d63.jpg`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://www.saucedemo.com/inventory.html`,
      },
      cookies: {},
    };

    url = http.url`https://www.saucedemo.com/static/media/bolt-shirt-1200x1500.c2599ac5f0a35ed5931e.jpg`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://www.saucedemo.com/inventory.html`,
      },
      cookies: {},
    };

    url = http.url`https://www.saucedemo.com/static/media/sauce-pullover-1200x1500.51d7ffaf301e698772c8.jpg`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://www.saucedemo.com/inventory.html`,
      },
      cookies: {},
    };

    url = http.url`https://www.saucedemo.com/static/media/red-onesie-1200x1500.2ec615b271ef4c3bc430.jpg`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://www.saucedemo.com/inventory.html`,
      },
      cookies: {},
    };

    url = http.url`https://www.saucedemo.com/static/media/red-tatt-1200x1500.30dadef477804e54fc7b.jpg`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://www.saucedemo.com/static/css/main.8a7d64a1.css`,
      },
      cookies: {},
    };

    url = http.url`https://www.saucedemo.com/static/media/cart3x.3669d74ad0f420aa005c.svg`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://www.saucedemo.com/static/css/main.8a7d64a1.css`,
      },
      cookies: {},
    };

    url = http.url`https://www.saucedemo.com/static/media/filter3x.2943df5bcabfd174febc.svg`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://www.saucedemo.com/static/css/main.8a7d64a1.css`,
      },
      cookies: {},
    };

    url = http.url`https://www.saucedemo.com/static/media/arrow3x.4b825b78b4bd5f987b7d.svg`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Content-type": `application/json`,
        Accept: `*/*`,
        Referer: `https://www.saucedemo.com/`,
      },
      cookies: {},
    };

    url = http.url`https://events.backtrace.io/api/summed-events/submit?universe=UNIVERSE&token=TOKEN`;
    resp = http.request(
      "POST",
      url,
      `{"application":"Swag Store","appversion":"3.0.0","summed_events":[{"timestamp":1780219521,"attributes":{"application.session":"27589fe0-8ff0-4c7e-9496-31ffc5b8598d","backtrace.agent":"@backtrace-labs/react","backtrace.version":"0.0.5","browser.name":"Chrome","browser.version":"148.0.0.0","engine.name":"Blink","engine.version":"148.0.0.0","browser.platform":"Win32","cpu.arch":"amd64","uname.sysname":"Windows","uname.version":"10","mobile":"false","user.agent.full":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36","application":"Swag Store","process.age":"0","hostname":"www.saucedemo.com","referrer":"https://www.saucedemo.com/","location.port":"","location.protocol":"https:","location.origin":"https://www.saucedemo.com","location.href":"https://www.saucedemo.com/","language":"en-US","cookies.enable":"true","document.domain":"www.saucedemo.com","document.baseURI":"https://www.saucedemo.com/","document.title":"Swag Labs","document.referrer":"","localstorage.enable":"true","window.innerHeight":"703","window.innerWidth":"1036","window.outerHeight":"798","window.outerWidth":"1051","window.pageXOffset":"0","window.pageYOffset":"0","window.screenX":"10","window.screenY":"10","window.screenLeft":"10","window.screenTop":"10","guid":"27589fe0-8ff0-4c7e-9496-31ffc5b8598d","application.version":"3.0.0"},"metric_group":"Application Launches"}],"metadata":{"dropped_events":1}}`,
      params,
    );

    check(resp, { "status equals 401": (r) => r.status === 401 });

    params = {
      headers: {
        "Content-type": `application/json`,
        Accept: `*/*`,
        Referer: `https://www.saucedemo.com/`,
      },
      cookies: {},
    };

    url = http.url`https://events.backtrace.io/api/unique-events/submit?universe=UNIVERSE&token=TOKEN`;
    resp = http.request(
      "POST",
      url,
      `{"application":"Swag Store","appversion":"3.0.0","unique_events":[{"timestamp":1780219521,"attributes":{"application.session":"27589fe0-8ff0-4c7e-9496-31ffc5b8598d","backtrace.agent":"@backtrace-labs/react","backtrace.version":"0.0.5","browser.name":"Chrome","browser.version":"148.0.0.0","engine.name":"Blink","engine.version":"148.0.0.0","browser.platform":"Win32","cpu.arch":"amd64","uname.sysname":"Windows","uname.version":"10","mobile":"false","user.agent.full":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36","application":"Swag Store","process.age":"0","hostname":"www.saucedemo.com","referrer":"https://www.saucedemo.com/","location.port":"","location.protocol":"https:","location.origin":"https://www.saucedemo.com","location.href":"https://www.saucedemo.com/","language":"en-US","cookies.enable":"true","document.domain":"www.saucedemo.com","document.baseURI":"https://www.saucedemo.com/","document.title":"Swag Labs","document.referrer":"","localstorage.enable":"true","window.innerHeight":"703","window.innerWidth":"1036","window.outerHeight":"798","window.outerWidth":"1051","window.pageXOffset":"0","window.pageYOffset":"0","window.screenX":"10","window.screenY":"10","window.screenLeft":"10","window.screenTop":"10","guid":"27589fe0-8ff0-4c7e-9496-31ffc5b8598d","application.version":"3.0.0"},"unique":["guid"]}],"metadata":{"dropped_events":1}}`,
      params,
    );

    check(resp, { "status equals 401": (r) => r.status === 401 });

    params = {
      headers: {
        "Content-type": `application/json`,
        Accept: `*/*`,
        Referer: `https://www.saucedemo.com/`,
      },
      cookies: {},
    };

    url = http.url`https://events.backtrace.io/api/summed-events/submit?universe=UNIVERSE&token=TOKEN`;
    resp = http.request(
      "POST",
      url,
      `{"application":"Swag Store","appversion":"3.0.0","summed_events":[{"timestamp":1780219542,"attributes":{"application.session":"27589fe0-8ff0-4c7e-9496-31ffc5b8598d","backtrace.agent":"@backtrace-labs/react","backtrace.version":"0.0.5","browser.name":"Chrome","browser.version":"148.0.0.0","engine.name":"Blink","engine.version":"148.0.0.0","browser.platform":"Win32","cpu.arch":"amd64","uname.sysname":"Windows","uname.version":"10","mobile":"false","user.agent.full":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36","application":"Swag Store","process.age":"0","hostname":"www.saucedemo.com","referrer":"https://www.saucedemo.com/","location.port":"","location.protocol":"https:","location.origin":"https://www.saucedemo.com","location.href":"https://www.saucedemo.com/","language":"en-US","cookies.enable":"true","document.domain":"www.saucedemo.com","document.baseURI":"https://www.saucedemo.com/","document.title":"Swag Labs","document.referrer":"","localstorage.enable":"true","window.innerHeight":"703","window.innerWidth":"1036","window.outerHeight":"798","window.outerWidth":"1051","window.pageXOffset":"0","window.pageYOffset":"0","window.screenX":"10","window.screenY":"10","window.screenLeft":"10","window.screenTop":"10","guid":"27589fe0-8ff0-4c7e-9496-31ffc5b8598d","application.version":"3.0.0"},"metric_group":"Application Launches"}],"metadata":{"dropped_events":2}}`,
      params,
    );

    check(resp, { "status equals 401": (r) => r.status === 401 });

    params = {
      headers: {
        "Content-type": `application/json`,
        Accept: `*/*`,
        Referer: `https://www.saucedemo.com/`,
      },
      cookies: {},
    };

    url = http.url`https://events.backtrace.io/api/unique-events/submit?universe=UNIVERSE&token=TOKEN`;
    resp = http.request(
      "POST",
      url,
      `{"application":"Swag Store","appversion":"3.0.0","unique_events":[{"timestamp":1780219542,"attributes":{"application.session":"27589fe0-8ff0-4c7e-9496-31ffc5b8598d","backtrace.agent":"@backtrace-labs/react","backtrace.version":"0.0.5","browser.name":"Chrome","browser.version":"148.0.0.0","engine.name":"Blink","engine.version":"148.0.0.0","browser.platform":"Win32","cpu.arch":"amd64","uname.sysname":"Windows","uname.version":"10","mobile":"false","user.agent.full":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36","application":"Swag Store","process.age":"0","hostname":"www.saucedemo.com","referrer":"https://www.saucedemo.com/","location.port":"","location.protocol":"https:","location.origin":"https://www.saucedemo.com","location.href":"https://www.saucedemo.com/","language":"en-US","cookies.enable":"true","document.domain":"www.saucedemo.com","document.baseURI":"https://www.saucedemo.com/","document.title":"Swag Labs","document.referrer":"","localstorage.enable":"true","window.innerHeight":"703","window.innerWidth":"1036","window.outerHeight":"798","window.outerWidth":"1051","window.pageXOffset":"0","window.pageYOffset":"0","window.screenX":"10","window.screenY":"10","window.screenLeft":"10","window.screenTop":"10","guid":"27589fe0-8ff0-4c7e-9496-31ffc5b8598d","application.version":"3.0.0"},"unique":["guid"]}],"metadata":{"dropped_events":2}}`,
      params,
    );

    check(resp, { "status equals 401": (r) => r.status === 401 });
  });
  sleep(1);
}
